// <auto-generated />
using System;
using BOG.DbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOG.DbModel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121160000_AddDocumentNumberToPlaintiff")]
    partial class AddDocumentNumberToPlaintiff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration builds on top of the current model snapshot
            // The model state is defined in ApplicationDbContextModelSnapshot.cs
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
